// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iks.proto

#ifndef PROTOBUF_iks_2eproto__INCLUDED
#define PROTOBUF_iks_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_iks_2eproto();
void protobuf_AssignDesc_iks_2eproto();
void protobuf_ShutdownFile_iks_2eproto();

class CMSG_AESOperation;
class CMSG_DesfireAuth_Step1;
class CMSG_DesfireAuth_Step2;
class CMSG_GenRandom;
class SMSG_AESResult;
class SMSG_DesfireAuth_Step1;
class SMSG_DesfireAuth_Step2;
class SMSG_GenRandom;

// ===================================================================

class CMSG_GenRandom : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSG_GenRandom) */ {
 public:
  CMSG_GenRandom();
  virtual ~CMSG_GenRandom();

  CMSG_GenRandom(const CMSG_GenRandom& from);

  inline CMSG_GenRandom& operator=(const CMSG_GenRandom& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMSG_GenRandom& default_instance();

  void Swap(CMSG_GenRandom* other);

  // implements Message ----------------------------------------------

  inline CMSG_GenRandom* New() const { return New(NULL); }

  CMSG_GenRandom* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMSG_GenRandom& from);
  void MergeFrom(const CMSG_GenRandom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMSG_GenRandom* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 size = 1;
  void clear_size();
  static const int kSizeFieldNumber = 1;
  ::google::protobuf::int32 size() const;
  void set_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CMSG_GenRandom)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 size_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static CMSG_GenRandom* default_instance_;
};
// -------------------------------------------------------------------

class SMSG_GenRandom : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SMSG_GenRandom) */ {
 public:
  SMSG_GenRandom();
  virtual ~SMSG_GenRandom();

  SMSG_GenRandom(const SMSG_GenRandom& from);

  inline SMSG_GenRandom& operator=(const SMSG_GenRandom& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SMSG_GenRandom& default_instance();

  void Swap(SMSG_GenRandom* other);

  // implements Message ----------------------------------------------

  inline SMSG_GenRandom* New() const { return New(NULL); }

  SMSG_GenRandom* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SMSG_GenRandom& from);
  void MergeFrom(const SMSG_GenRandom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMSG_GenRandom* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes randomBytes = 1;
  void clear_randombytes();
  static const int kRandomBytesFieldNumber = 1;
  const ::std::string& randombytes() const;
  void set_randombytes(const ::std::string& value);
  void set_randombytes(const char* value);
  void set_randombytes(const void* value, size_t size);
  ::std::string* mutable_randombytes();
  ::std::string* release_randombytes();
  void set_allocated_randombytes(::std::string* randombytes);

  // @@protoc_insertion_point(class_scope:SMSG_GenRandom)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr randombytes_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static SMSG_GenRandom* default_instance_;
};
// -------------------------------------------------------------------

class CMSG_AESOperation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSG_AESOperation) */ {
 public:
  CMSG_AESOperation();
  virtual ~CMSG_AESOperation();

  CMSG_AESOperation(const CMSG_AESOperation& from);

  inline CMSG_AESOperation& operator=(const CMSG_AESOperation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMSG_AESOperation& default_instance();

  void Swap(CMSG_AESOperation* other);

  // implements Message ----------------------------------------------

  inline CMSG_AESOperation* New() const { return New(NULL); }

  CMSG_AESOperation* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMSG_AESOperation& from);
  void MergeFrom(const CMSG_AESOperation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMSG_AESOperation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key_uuid = 1;
  void clear_key_uuid();
  static const int kKeyUuidFieldNumber = 1;
  const ::std::string& key_uuid() const;
  void set_key_uuid(const ::std::string& value);
  void set_key_uuid(const char* value);
  void set_key_uuid(const char* value, size_t size);
  ::std::string* mutable_key_uuid();
  ::std::string* release_key_uuid();
  void set_allocated_key_uuid(::std::string* key_uuid);

  // optional bytes payload = 3;
  void clear_payload();
  static const int kPayloadFieldNumber = 3;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // optional bytes iv = 4;
  void clear_iv();
  static const int kIvFieldNumber = 4;
  const ::std::string& iv() const;
  void set_iv(const ::std::string& value);
  void set_iv(const char* value);
  void set_iv(const void* value, size_t size);
  ::std::string* mutable_iv();
  ::std::string* release_iv();
  void set_allocated_iv(::std::string* iv);

  // optional bool request_signature = 5;
  void clear_request_signature();
  static const int kRequestSignatureFieldNumber = 5;
  bool request_signature() const;
  void set_request_signature(bool value);

  // @@protoc_insertion_point(class_scope:CMSG_AESOperation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr key_uuid_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::internal::ArenaStringPtr iv_;
  bool request_signature_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static CMSG_AESOperation* default_instance_;
};
// -------------------------------------------------------------------

class SMSG_AESResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SMSG_AESResult) */ {
 public:
  SMSG_AESResult();
  virtual ~SMSG_AESResult();

  SMSG_AESResult(const SMSG_AESResult& from);

  inline SMSG_AESResult& operator=(const SMSG_AESResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SMSG_AESResult& default_instance();

  void Swap(SMSG_AESResult* other);

  // implements Message ----------------------------------------------

  inline SMSG_AESResult* New() const { return New(NULL); }

  SMSG_AESResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SMSG_AESResult& from);
  void MergeFrom(const SMSG_AESResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMSG_AESResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bytes payload = 1;
  void clear_payload();
  static const int kPayloadFieldNumber = 1;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // optional bytes signature = 2;
  void clear_signature();
  static const int kSignatureFieldNumber = 2;
  const ::std::string& signature() const;
  void set_signature(const ::std::string& value);
  void set_signature(const char* value);
  void set_signature(const void* value, size_t size);
  ::std::string* mutable_signature();
  ::std::string* release_signature();
  void set_allocated_signature(::std::string* signature);

  // @@protoc_insertion_point(class_scope:SMSG_AESResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::internal::ArenaStringPtr signature_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static SMSG_AESResult* default_instance_;
};
// -------------------------------------------------------------------

class CMSG_DesfireAuth_Step1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSG_DesfireAuth_Step1) */ {
 public:
  CMSG_DesfireAuth_Step1();
  virtual ~CMSG_DesfireAuth_Step1();

  CMSG_DesfireAuth_Step1(const CMSG_DesfireAuth_Step1& from);

  inline CMSG_DesfireAuth_Step1& operator=(const CMSG_DesfireAuth_Step1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMSG_DesfireAuth_Step1& default_instance();

  void Swap(CMSG_DesfireAuth_Step1* other);

  // implements Message ----------------------------------------------

  inline CMSG_DesfireAuth_Step1* New() const { return New(NULL); }

  CMSG_DesfireAuth_Step1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMSG_DesfireAuth_Step1& from);
  void MergeFrom(const CMSG_DesfireAuth_Step1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMSG_DesfireAuth_Step1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key_uuid = 1;
  void clear_key_uuid();
  static const int kKeyUuidFieldNumber = 1;
  const ::std::string& key_uuid() const;
  void set_key_uuid(const ::std::string& value);
  void set_key_uuid(const char* value);
  void set_key_uuid(const char* value, size_t size);
  ::std::string* mutable_key_uuid();
  ::std::string* release_key_uuid();
  void set_allocated_key_uuid(::std::string* key_uuid);

  // optional bytes random_picc = 3;
  void clear_random_picc();
  static const int kRandomPiccFieldNumber = 3;
  const ::std::string& random_picc() const;
  void set_random_picc(const ::std::string& value);
  void set_random_picc(const char* value);
  void set_random_picc(const void* value, size_t size);
  ::std::string* mutable_random_picc();
  ::std::string* release_random_picc();
  void set_allocated_random_picc(::std::string* random_picc);

  // @@protoc_insertion_point(class_scope:CMSG_DesfireAuth_Step1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr key_uuid_;
  ::google::protobuf::internal::ArenaStringPtr random_picc_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static CMSG_DesfireAuth_Step1* default_instance_;
};
// -------------------------------------------------------------------

class SMSG_DesfireAuth_Step1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SMSG_DesfireAuth_Step1) */ {
 public:
  SMSG_DesfireAuth_Step1();
  virtual ~SMSG_DesfireAuth_Step1();

  SMSG_DesfireAuth_Step1(const SMSG_DesfireAuth_Step1& from);

  inline SMSG_DesfireAuth_Step1& operator=(const SMSG_DesfireAuth_Step1& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SMSG_DesfireAuth_Step1& default_instance();

  void Swap(SMSG_DesfireAuth_Step1* other);

  // implements Message ----------------------------------------------

  inline SMSG_DesfireAuth_Step1* New() const { return New(NULL); }

  SMSG_DesfireAuth_Step1* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SMSG_DesfireAuth_Step1& from);
  void MergeFrom(const SMSG_DesfireAuth_Step1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMSG_DesfireAuth_Step1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // optional bytes random2 = 2;
  void clear_random2();
  static const int kRandom2FieldNumber = 2;
  const ::std::string& random2() const;
  void set_random2(const ::std::string& value);
  void set_random2(const char* value);
  void set_random2(const void* value, size_t size);
  ::std::string* mutable_random2();
  ::std::string* release_random2();
  void set_allocated_random2(::std::string* random2);

  // optional bytes encrypted_cryptogram = 3;
  void clear_encrypted_cryptogram();
  static const int kEncryptedCryptogramFieldNumber = 3;
  const ::std::string& encrypted_cryptogram() const;
  void set_encrypted_cryptogram(const ::std::string& value);
  void set_encrypted_cryptogram(const char* value);
  void set_encrypted_cryptogram(const void* value, size_t size);
  ::std::string* mutable_encrypted_cryptogram();
  ::std::string* release_encrypted_cryptogram();
  void set_allocated_encrypted_cryptogram(::std::string* encrypted_cryptogram);

  // optional bytes auth_context_id = 4;
  void clear_auth_context_id();
  static const int kAuthContextIdFieldNumber = 4;
  const ::std::string& auth_context_id() const;
  void set_auth_context_id(const ::std::string& value);
  void set_auth_context_id(const char* value);
  void set_auth_context_id(const void* value, size_t size);
  ::std::string* mutable_auth_context_id();
  ::std::string* release_auth_context_id();
  void set_allocated_auth_context_id(::std::string* auth_context_id);

  // @@protoc_insertion_point(class_scope:SMSG_DesfireAuth_Step1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr random2_;
  ::google::protobuf::internal::ArenaStringPtr encrypted_cryptogram_;
  ::google::protobuf::internal::ArenaStringPtr auth_context_id_;
  bool success_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static SMSG_DesfireAuth_Step1* default_instance_;
};
// -------------------------------------------------------------------

class CMSG_DesfireAuth_Step2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSG_DesfireAuth_Step2) */ {
 public:
  CMSG_DesfireAuth_Step2();
  virtual ~CMSG_DesfireAuth_Step2();

  CMSG_DesfireAuth_Step2(const CMSG_DesfireAuth_Step2& from);

  inline CMSG_DesfireAuth_Step2& operator=(const CMSG_DesfireAuth_Step2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMSG_DesfireAuth_Step2& default_instance();

  void Swap(CMSG_DesfireAuth_Step2* other);

  // implements Message ----------------------------------------------

  inline CMSG_DesfireAuth_Step2* New() const { return New(NULL); }

  CMSG_DesfireAuth_Step2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMSG_DesfireAuth_Step2& from);
  void MergeFrom(const CMSG_DesfireAuth_Step2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CMSG_DesfireAuth_Step2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key_uuid = 1;
  void clear_key_uuid();
  static const int kKeyUuidFieldNumber = 1;
  const ::std::string& key_uuid() const;
  void set_key_uuid(const ::std::string& value);
  void set_key_uuid(const char* value);
  void set_key_uuid(const char* value, size_t size);
  ::std::string* mutable_key_uuid();
  ::std::string* release_key_uuid();
  void set_allocated_key_uuid(::std::string* key_uuid);

  // optional bytes picc_cryptogram = 2;
  void clear_picc_cryptogram();
  static const int kPiccCryptogramFieldNumber = 2;
  const ::std::string& picc_cryptogram() const;
  void set_picc_cryptogram(const ::std::string& value);
  void set_picc_cryptogram(const char* value);
  void set_picc_cryptogram(const void* value, size_t size);
  ::std::string* mutable_picc_cryptogram();
  ::std::string* release_picc_cryptogram();
  void set_allocated_picc_cryptogram(::std::string* picc_cryptogram);

  // optional bytes auth_context_id = 3;
  void clear_auth_context_id();
  static const int kAuthContextIdFieldNumber = 3;
  const ::std::string& auth_context_id() const;
  void set_auth_context_id(const ::std::string& value);
  void set_auth_context_id(const char* value);
  void set_auth_context_id(const void* value, size_t size);
  ::std::string* mutable_auth_context_id();
  ::std::string* release_auth_context_id();
  void set_allocated_auth_context_id(::std::string* auth_context_id);

  // @@protoc_insertion_point(class_scope:CMSG_DesfireAuth_Step2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr key_uuid_;
  ::google::protobuf::internal::ArenaStringPtr picc_cryptogram_;
  ::google::protobuf::internal::ArenaStringPtr auth_context_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static CMSG_DesfireAuth_Step2* default_instance_;
};
// -------------------------------------------------------------------

class SMSG_DesfireAuth_Step2 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:SMSG_DesfireAuth_Step2) */ {
 public:
  SMSG_DesfireAuth_Step2();
  virtual ~SMSG_DesfireAuth_Step2();

  SMSG_DesfireAuth_Step2(const SMSG_DesfireAuth_Step2& from);

  inline SMSG_DesfireAuth_Step2& operator=(const SMSG_DesfireAuth_Step2& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SMSG_DesfireAuth_Step2& default_instance();

  void Swap(SMSG_DesfireAuth_Step2* other);

  // implements Message ----------------------------------------------

  inline SMSG_DesfireAuth_Step2* New() const { return New(NULL); }

  SMSG_DesfireAuth_Step2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SMSG_DesfireAuth_Step2& from);
  void MergeFrom(const SMSG_DesfireAuth_Step2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SMSG_DesfireAuth_Step2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // optional bytes session_key = 2;
  void clear_session_key();
  static const int kSessionKeyFieldNumber = 2;
  const ::std::string& session_key() const;
  void set_session_key(const ::std::string& value);
  void set_session_key(const char* value);
  void set_session_key(const void* value, size_t size);
  ::std::string* mutable_session_key();
  ::std::string* release_session_key();
  void set_allocated_session_key(::std::string* session_key);

  // optional string session_key_ref = 3;
  void clear_session_key_ref();
  static const int kSessionKeyRefFieldNumber = 3;
  const ::std::string& session_key_ref() const;
  void set_session_key_ref(const ::std::string& value);
  void set_session_key_ref(const char* value);
  void set_session_key_ref(const char* value, size_t size);
  ::std::string* mutable_session_key_ref();
  ::std::string* release_session_key_ref();
  void set_allocated_session_key_ref(::std::string* session_key_ref);

  // @@protoc_insertion_point(class_scope:SMSG_DesfireAuth_Step2)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr session_key_;
  ::google::protobuf::internal::ArenaStringPtr session_key_ref_;
  bool success_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_iks_2eproto();
  friend void protobuf_AssignDesc_iks_2eproto();
  friend void protobuf_ShutdownFile_iks_2eproto();

  void InitAsDefaultInstance();
  static SMSG_DesfireAuth_Step2* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CMSG_GenRandom

// optional int32 size = 1;
inline void CMSG_GenRandom::clear_size() {
  size_ = 0;
}
inline ::google::protobuf::int32 CMSG_GenRandom::size() const {
  // @@protoc_insertion_point(field_get:CMSG_GenRandom.size)
  return size_;
}
inline void CMSG_GenRandom::set_size(::google::protobuf::int32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:CMSG_GenRandom.size)
}

// -------------------------------------------------------------------

// SMSG_GenRandom

// optional bytes randomBytes = 1;
inline void SMSG_GenRandom::clear_randombytes() {
  randombytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_GenRandom::randombytes() const {
  // @@protoc_insertion_point(field_get:SMSG_GenRandom.randomBytes)
  return randombytes_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_GenRandom::set_randombytes(const ::std::string& value) {
  
  randombytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_GenRandom.randomBytes)
}
inline void SMSG_GenRandom::set_randombytes(const char* value) {
  
  randombytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_GenRandom.randomBytes)
}
inline void SMSG_GenRandom::set_randombytes(const void* value, size_t size) {
  
  randombytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_GenRandom.randomBytes)
}
inline ::std::string* SMSG_GenRandom::mutable_randombytes() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_GenRandom.randomBytes)
  return randombytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_GenRandom::release_randombytes() {
  // @@protoc_insertion_point(field_release:SMSG_GenRandom.randomBytes)
  
  return randombytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_GenRandom::set_allocated_randombytes(::std::string* randombytes) {
  if (randombytes != NULL) {
    
  } else {
    
  }
  randombytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), randombytes);
  // @@protoc_insertion_point(field_set_allocated:SMSG_GenRandom.randomBytes)
}

// -------------------------------------------------------------------

// CMSG_AESOperation

// optional string key_uuid = 1;
inline void CMSG_AESOperation::clear_key_uuid() {
  key_uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_AESOperation::key_uuid() const {
  // @@protoc_insertion_point(field_get:CMSG_AESOperation.key_uuid)
  return key_uuid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_key_uuid(const ::std::string& value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_AESOperation.key_uuid)
}
inline void CMSG_AESOperation::set_key_uuid(const char* value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_AESOperation.key_uuid)
}
inline void CMSG_AESOperation::set_key_uuid(const char* value, size_t size) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_AESOperation.key_uuid)
}
inline ::std::string* CMSG_AESOperation::mutable_key_uuid() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_AESOperation.key_uuid)
  return key_uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_AESOperation::release_key_uuid() {
  // @@protoc_insertion_point(field_release:CMSG_AESOperation.key_uuid)
  
  return key_uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_allocated_key_uuid(::std::string* key_uuid) {
  if (key_uuid != NULL) {
    
  } else {
    
  }
  key_uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_uuid);
  // @@protoc_insertion_point(field_set_allocated:CMSG_AESOperation.key_uuid)
}

// optional bytes payload = 3;
inline void CMSG_AESOperation::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_AESOperation::payload() const {
  // @@protoc_insertion_point(field_get:CMSG_AESOperation.payload)
  return payload_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_AESOperation.payload)
}
inline void CMSG_AESOperation::set_payload(const char* value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_AESOperation.payload)
}
inline void CMSG_AESOperation::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_AESOperation.payload)
}
inline ::std::string* CMSG_AESOperation::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_AESOperation.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_AESOperation::release_payload() {
  // @@protoc_insertion_point(field_release:CMSG_AESOperation.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:CMSG_AESOperation.payload)
}

// optional bytes iv = 4;
inline void CMSG_AESOperation::clear_iv() {
  iv_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_AESOperation::iv() const {
  // @@protoc_insertion_point(field_get:CMSG_AESOperation.iv)
  return iv_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_iv(const ::std::string& value) {
  
  iv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_AESOperation.iv)
}
inline void CMSG_AESOperation::set_iv(const char* value) {
  
  iv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_AESOperation.iv)
}
inline void CMSG_AESOperation::set_iv(const void* value, size_t size) {
  
  iv_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_AESOperation.iv)
}
inline ::std::string* CMSG_AESOperation::mutable_iv() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_AESOperation.iv)
  return iv_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_AESOperation::release_iv() {
  // @@protoc_insertion_point(field_release:CMSG_AESOperation.iv)
  
  return iv_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_AESOperation::set_allocated_iv(::std::string* iv) {
  if (iv != NULL) {
    
  } else {
    
  }
  iv_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), iv);
  // @@protoc_insertion_point(field_set_allocated:CMSG_AESOperation.iv)
}

// optional bool request_signature = 5;
inline void CMSG_AESOperation::clear_request_signature() {
  request_signature_ = false;
}
inline bool CMSG_AESOperation::request_signature() const {
  // @@protoc_insertion_point(field_get:CMSG_AESOperation.request_signature)
  return request_signature_;
}
inline void CMSG_AESOperation::set_request_signature(bool value) {
  
  request_signature_ = value;
  // @@protoc_insertion_point(field_set:CMSG_AESOperation.request_signature)
}

// -------------------------------------------------------------------

// SMSG_AESResult

// optional bytes payload = 1;
inline void SMSG_AESResult::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_AESResult::payload() const {
  // @@protoc_insertion_point(field_get:SMSG_AESResult.payload)
  return payload_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_AESResult::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_AESResult.payload)
}
inline void SMSG_AESResult::set_payload(const char* value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_AESResult.payload)
}
inline void SMSG_AESResult::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_AESResult.payload)
}
inline ::std::string* SMSG_AESResult::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_AESResult.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_AESResult::release_payload() {
  // @@protoc_insertion_point(field_release:SMSG_AESResult.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_AESResult::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:SMSG_AESResult.payload)
}

// optional bytes signature = 2;
inline void SMSG_AESResult::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_AESResult::signature() const {
  // @@protoc_insertion_point(field_get:SMSG_AESResult.signature)
  return signature_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_AESResult::set_signature(const ::std::string& value) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_AESResult.signature)
}
inline void SMSG_AESResult::set_signature(const char* value) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_AESResult.signature)
}
inline void SMSG_AESResult::set_signature(const void* value, size_t size) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_AESResult.signature)
}
inline ::std::string* SMSG_AESResult::mutable_signature() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_AESResult.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_AESResult::release_signature() {
  // @@protoc_insertion_point(field_release:SMSG_AESResult.signature)
  
  return signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_AESResult::set_allocated_signature(::std::string* signature) {
  if (signature != NULL) {
    
  } else {
    
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:SMSG_AESResult.signature)
}

// -------------------------------------------------------------------

// CMSG_DesfireAuth_Step1

// optional string key_uuid = 1;
inline void CMSG_DesfireAuth_Step1::clear_key_uuid() {
  key_uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_DesfireAuth_Step1::key_uuid() const {
  // @@protoc_insertion_point(field_get:CMSG_DesfireAuth_Step1.key_uuid)
  return key_uuid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step1::set_key_uuid(const ::std::string& value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_DesfireAuth_Step1.key_uuid)
}
inline void CMSG_DesfireAuth_Step1::set_key_uuid(const char* value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_DesfireAuth_Step1.key_uuid)
}
inline void CMSG_DesfireAuth_Step1::set_key_uuid(const char* value, size_t size) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_DesfireAuth_Step1.key_uuid)
}
inline ::std::string* CMSG_DesfireAuth_Step1::mutable_key_uuid() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_DesfireAuth_Step1.key_uuid)
  return key_uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_DesfireAuth_Step1::release_key_uuid() {
  // @@protoc_insertion_point(field_release:CMSG_DesfireAuth_Step1.key_uuid)
  
  return key_uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step1::set_allocated_key_uuid(::std::string* key_uuid) {
  if (key_uuid != NULL) {
    
  } else {
    
  }
  key_uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_uuid);
  // @@protoc_insertion_point(field_set_allocated:CMSG_DesfireAuth_Step1.key_uuid)
}

// optional bytes random_picc = 3;
inline void CMSG_DesfireAuth_Step1::clear_random_picc() {
  random_picc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_DesfireAuth_Step1::random_picc() const {
  // @@protoc_insertion_point(field_get:CMSG_DesfireAuth_Step1.random_picc)
  return random_picc_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step1::set_random_picc(const ::std::string& value) {
  
  random_picc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_DesfireAuth_Step1.random_picc)
}
inline void CMSG_DesfireAuth_Step1::set_random_picc(const char* value) {
  
  random_picc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_DesfireAuth_Step1.random_picc)
}
inline void CMSG_DesfireAuth_Step1::set_random_picc(const void* value, size_t size) {
  
  random_picc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_DesfireAuth_Step1.random_picc)
}
inline ::std::string* CMSG_DesfireAuth_Step1::mutable_random_picc() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_DesfireAuth_Step1.random_picc)
  return random_picc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_DesfireAuth_Step1::release_random_picc() {
  // @@protoc_insertion_point(field_release:CMSG_DesfireAuth_Step1.random_picc)
  
  return random_picc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step1::set_allocated_random_picc(::std::string* random_picc) {
  if (random_picc != NULL) {
    
  } else {
    
  }
  random_picc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), random_picc);
  // @@protoc_insertion_point(field_set_allocated:CMSG_DesfireAuth_Step1.random_picc)
}

// -------------------------------------------------------------------

// SMSG_DesfireAuth_Step1

// optional bool success = 1;
inline void SMSG_DesfireAuth_Step1::clear_success() {
  success_ = false;
}
inline bool SMSG_DesfireAuth_Step1::success() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step1.success)
  return success_;
}
inline void SMSG_DesfireAuth_Step1::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step1.success)
}

// optional bytes random2 = 2;
inline void SMSG_DesfireAuth_Step1::clear_random2() {
  random2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_DesfireAuth_Step1::random2() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step1.random2)
  return random2_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_random2(const ::std::string& value) {
  
  random2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step1.random2)
}
inline void SMSG_DesfireAuth_Step1::set_random2(const char* value) {
  
  random2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_DesfireAuth_Step1.random2)
}
inline void SMSG_DesfireAuth_Step1::set_random2(const void* value, size_t size) {
  
  random2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_DesfireAuth_Step1.random2)
}
inline ::std::string* SMSG_DesfireAuth_Step1::mutable_random2() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_DesfireAuth_Step1.random2)
  return random2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_DesfireAuth_Step1::release_random2() {
  // @@protoc_insertion_point(field_release:SMSG_DesfireAuth_Step1.random2)
  
  return random2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_allocated_random2(::std::string* random2) {
  if (random2 != NULL) {
    
  } else {
    
  }
  random2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), random2);
  // @@protoc_insertion_point(field_set_allocated:SMSG_DesfireAuth_Step1.random2)
}

// optional bytes encrypted_cryptogram = 3;
inline void SMSG_DesfireAuth_Step1::clear_encrypted_cryptogram() {
  encrypted_cryptogram_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_DesfireAuth_Step1::encrypted_cryptogram() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
  return encrypted_cryptogram_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_encrypted_cryptogram(const ::std::string& value) {
  
  encrypted_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
}
inline void SMSG_DesfireAuth_Step1::set_encrypted_cryptogram(const char* value) {
  
  encrypted_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
}
inline void SMSG_DesfireAuth_Step1::set_encrypted_cryptogram(const void* value, size_t size) {
  
  encrypted_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
}
inline ::std::string* SMSG_DesfireAuth_Step1::mutable_encrypted_cryptogram() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
  return encrypted_cryptogram_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_DesfireAuth_Step1::release_encrypted_cryptogram() {
  // @@protoc_insertion_point(field_release:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
  
  return encrypted_cryptogram_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_allocated_encrypted_cryptogram(::std::string* encrypted_cryptogram) {
  if (encrypted_cryptogram != NULL) {
    
  } else {
    
  }
  encrypted_cryptogram_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), encrypted_cryptogram);
  // @@protoc_insertion_point(field_set_allocated:SMSG_DesfireAuth_Step1.encrypted_cryptogram)
}

// optional bytes auth_context_id = 4;
inline void SMSG_DesfireAuth_Step1::clear_auth_context_id() {
  auth_context_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_DesfireAuth_Step1::auth_context_id() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step1.auth_context_id)
  return auth_context_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_auth_context_id(const ::std::string& value) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step1.auth_context_id)
}
inline void SMSG_DesfireAuth_Step1::set_auth_context_id(const char* value) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_DesfireAuth_Step1.auth_context_id)
}
inline void SMSG_DesfireAuth_Step1::set_auth_context_id(const void* value, size_t size) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_DesfireAuth_Step1.auth_context_id)
}
inline ::std::string* SMSG_DesfireAuth_Step1::mutable_auth_context_id() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_DesfireAuth_Step1.auth_context_id)
  return auth_context_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_DesfireAuth_Step1::release_auth_context_id() {
  // @@protoc_insertion_point(field_release:SMSG_DesfireAuth_Step1.auth_context_id)
  
  return auth_context_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step1::set_allocated_auth_context_id(::std::string* auth_context_id) {
  if (auth_context_id != NULL) {
    
  } else {
    
  }
  auth_context_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), auth_context_id);
  // @@protoc_insertion_point(field_set_allocated:SMSG_DesfireAuth_Step1.auth_context_id)
}

// -------------------------------------------------------------------

// CMSG_DesfireAuth_Step2

// optional string key_uuid = 1;
inline void CMSG_DesfireAuth_Step2::clear_key_uuid() {
  key_uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_DesfireAuth_Step2::key_uuid() const {
  // @@protoc_insertion_point(field_get:CMSG_DesfireAuth_Step2.key_uuid)
  return key_uuid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_key_uuid(const ::std::string& value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_DesfireAuth_Step2.key_uuid)
}
inline void CMSG_DesfireAuth_Step2::set_key_uuid(const char* value) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_DesfireAuth_Step2.key_uuid)
}
inline void CMSG_DesfireAuth_Step2::set_key_uuid(const char* value, size_t size) {
  
  key_uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_DesfireAuth_Step2.key_uuid)
}
inline ::std::string* CMSG_DesfireAuth_Step2::mutable_key_uuid() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_DesfireAuth_Step2.key_uuid)
  return key_uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_DesfireAuth_Step2::release_key_uuid() {
  // @@protoc_insertion_point(field_release:CMSG_DesfireAuth_Step2.key_uuid)
  
  return key_uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_allocated_key_uuid(::std::string* key_uuid) {
  if (key_uuid != NULL) {
    
  } else {
    
  }
  key_uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key_uuid);
  // @@protoc_insertion_point(field_set_allocated:CMSG_DesfireAuth_Step2.key_uuid)
}

// optional bytes picc_cryptogram = 2;
inline void CMSG_DesfireAuth_Step2::clear_picc_cryptogram() {
  picc_cryptogram_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_DesfireAuth_Step2::picc_cryptogram() const {
  // @@protoc_insertion_point(field_get:CMSG_DesfireAuth_Step2.picc_cryptogram)
  return picc_cryptogram_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_picc_cryptogram(const ::std::string& value) {
  
  picc_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_DesfireAuth_Step2.picc_cryptogram)
}
inline void CMSG_DesfireAuth_Step2::set_picc_cryptogram(const char* value) {
  
  picc_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_DesfireAuth_Step2.picc_cryptogram)
}
inline void CMSG_DesfireAuth_Step2::set_picc_cryptogram(const void* value, size_t size) {
  
  picc_cryptogram_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_DesfireAuth_Step2.picc_cryptogram)
}
inline ::std::string* CMSG_DesfireAuth_Step2::mutable_picc_cryptogram() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_DesfireAuth_Step2.picc_cryptogram)
  return picc_cryptogram_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_DesfireAuth_Step2::release_picc_cryptogram() {
  // @@protoc_insertion_point(field_release:CMSG_DesfireAuth_Step2.picc_cryptogram)
  
  return picc_cryptogram_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_allocated_picc_cryptogram(::std::string* picc_cryptogram) {
  if (picc_cryptogram != NULL) {
    
  } else {
    
  }
  picc_cryptogram_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), picc_cryptogram);
  // @@protoc_insertion_point(field_set_allocated:CMSG_DesfireAuth_Step2.picc_cryptogram)
}

// optional bytes auth_context_id = 3;
inline void CMSG_DesfireAuth_Step2::clear_auth_context_id() {
  auth_context_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CMSG_DesfireAuth_Step2::auth_context_id() const {
  // @@protoc_insertion_point(field_get:CMSG_DesfireAuth_Step2.auth_context_id)
  return auth_context_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_auth_context_id(const ::std::string& value) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSG_DesfireAuth_Step2.auth_context_id)
}
inline void CMSG_DesfireAuth_Step2::set_auth_context_id(const char* value) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSG_DesfireAuth_Step2.auth_context_id)
}
inline void CMSG_DesfireAuth_Step2::set_auth_context_id(const void* value, size_t size) {
  
  auth_context_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSG_DesfireAuth_Step2.auth_context_id)
}
inline ::std::string* CMSG_DesfireAuth_Step2::mutable_auth_context_id() {
  
  // @@protoc_insertion_point(field_mutable:CMSG_DesfireAuth_Step2.auth_context_id)
  return auth_context_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CMSG_DesfireAuth_Step2::release_auth_context_id() {
  // @@protoc_insertion_point(field_release:CMSG_DesfireAuth_Step2.auth_context_id)
  
  return auth_context_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CMSG_DesfireAuth_Step2::set_allocated_auth_context_id(::std::string* auth_context_id) {
  if (auth_context_id != NULL) {
    
  } else {
    
  }
  auth_context_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), auth_context_id);
  // @@protoc_insertion_point(field_set_allocated:CMSG_DesfireAuth_Step2.auth_context_id)
}

// -------------------------------------------------------------------

// SMSG_DesfireAuth_Step2

// optional bool success = 1;
inline void SMSG_DesfireAuth_Step2::clear_success() {
  success_ = false;
}
inline bool SMSG_DesfireAuth_Step2::success() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step2.success)
  return success_;
}
inline void SMSG_DesfireAuth_Step2::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step2.success)
}

// optional bytes session_key = 2;
inline void SMSG_DesfireAuth_Step2::clear_session_key() {
  session_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_DesfireAuth_Step2::session_key() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step2.session_key)
  return session_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step2::set_session_key(const ::std::string& value) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step2.session_key)
}
inline void SMSG_DesfireAuth_Step2::set_session_key(const char* value) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_DesfireAuth_Step2.session_key)
}
inline void SMSG_DesfireAuth_Step2::set_session_key(const void* value, size_t size) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_DesfireAuth_Step2.session_key)
}
inline ::std::string* SMSG_DesfireAuth_Step2::mutable_session_key() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_DesfireAuth_Step2.session_key)
  return session_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_DesfireAuth_Step2::release_session_key() {
  // @@protoc_insertion_point(field_release:SMSG_DesfireAuth_Step2.session_key)
  
  return session_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step2::set_allocated_session_key(::std::string* session_key) {
  if (session_key != NULL) {
    
  } else {
    
  }
  session_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_key);
  // @@protoc_insertion_point(field_set_allocated:SMSG_DesfireAuth_Step2.session_key)
}

// optional string session_key_ref = 3;
inline void SMSG_DesfireAuth_Step2::clear_session_key_ref() {
  session_key_ref_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SMSG_DesfireAuth_Step2::session_key_ref() const {
  // @@protoc_insertion_point(field_get:SMSG_DesfireAuth_Step2.session_key_ref)
  return session_key_ref_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step2::set_session_key_ref(const ::std::string& value) {
  
  session_key_ref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SMSG_DesfireAuth_Step2.session_key_ref)
}
inline void SMSG_DesfireAuth_Step2::set_session_key_ref(const char* value) {
  
  session_key_ref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SMSG_DesfireAuth_Step2.session_key_ref)
}
inline void SMSG_DesfireAuth_Step2::set_session_key_ref(const char* value, size_t size) {
  
  session_key_ref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SMSG_DesfireAuth_Step2.session_key_ref)
}
inline ::std::string* SMSG_DesfireAuth_Step2::mutable_session_key_ref() {
  
  // @@protoc_insertion_point(field_mutable:SMSG_DesfireAuth_Step2.session_key_ref)
  return session_key_ref_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SMSG_DesfireAuth_Step2::release_session_key_ref() {
  // @@protoc_insertion_point(field_release:SMSG_DesfireAuth_Step2.session_key_ref)
  
  return session_key_ref_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SMSG_DesfireAuth_Step2::set_allocated_session_key_ref(::std::string* session_key_ref) {
  if (session_key_ref != NULL) {
    
  } else {
    
  }
  session_key_ref_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_key_ref);
  // @@protoc_insertion_point(field_set_allocated:SMSG_DesfireAuth_Step2.session_key_ref)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_iks_2eproto__INCLUDED
